openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0
servers:
  - url: http://localhost:9999/gendemo/api
#tags:
#  - name: user
#    description: Endpoints related to users.
paths:
  /users:
    get:
#      tags:
#        - user
      summary: Retrieve all users
      operationId: getUsers
      responses:
        '200':
          description: Successful operation
  /users/{id}:
    get:
#      tags:
#        - user
      summary: Retrieve a user by ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: ID of the user to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
        '404':
          description: User not found